name: Build and Push Validator Docker Image

on:
  push:
    branches:
      - dev-pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get the short SHA for tagging the image
      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build --platform=linux/amd64 \
            -t ghcr.io/${{ github.repository }}/server:dev-${{ env.SHORT_SHA }} \
            -f dev.Dockerfile --push .

